stages:
  - verify
  - deploy

variables:
  APP_NAME: rest-api-guide
  VERSION: 1.1.$CI_PIPELINE_IID

push:
  stage: deploy
  script:
    - git config --global user.email $OPEN_SOURCE_GITHUB_EMAIL
    - git config --global user.name $OPEN_SOURCE_GITHUB_LOGIN
    - git push https://$OPEN_SOURCE_GITHUB_LOGIN:$OPEN_SOURCE_GITHUB_TOKEN@github.com/Raiffeisen-DGTL/$APP_NAME.git HEAD:main --force
  only:
    - master
