rules:
  openapi-tags-alphabetical:
    description: Tags должны быть в алфавитном порядке
    documentationUrl: https://gitlabci.raiffeisen.ru/cib/api-guide/-/tree/master/spectral/rules/openapi?ref_type=heads#openapi-tags-alphabetical
    severity: info
    resolved: false
    given: '$'
    then:
      field: 'tags'
      function: alphabetical
      functionOptions:
        keyedBy: 'name'
