#!/bin/bash

# Script to build Spectral rulesets using yq
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"


echo "Building required ruleset..."
echo "# AUTOGENERATED - DO NOT EDIT THIS FILE MANUALLY" > required-ruleset.yaml
echo "documentationUrl: https://gitlabci.raiffeisen.ru/cib/api-guide/-/tree/master/spectral/rules" >> required-ruleset.yaml
yq ea '. as $i ireduce ({}; . *+ $i) | .. |= (select(tag == "!!seq") | unique) | sort_keys(..) | del(.functionsDir)' "$SCRIPT_DIR/rules/required"/*.yaml >> required-ruleset.yaml

echo "Building base ruleset..."
echo "# AUTOGENERATED - DO NOT EDIT THIS FILE MANUALLY" > base-ruleset.yaml
echo "documentationUrl: https://gitlabci.raiffeisen.ru/cib/api-guide/-/tree/master/spectral/rules" >> base-ruleset.yaml
yq ea '. as $i ireduce ({}; . *+ $i) | .. |= (select(tag == "!!seq") | unique) | sort_keys(..) | del(.functionsDir)' "$SCRIPT_DIR/rules/required"/*.yaml "$SCRIPT_DIR/rules/base"/*.yaml >> base-ruleset.yaml


echo "Rulesets built successfully!"